//
//  AnimeListRouter.swift
//  Codable_Clean
//
//  Created by OuSS on 5/11/19.
//  Copyright (c) 2019 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AnimeListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AnimeListDataPassing
{
  var dataStore: AnimeListDataStore? { get }
}

class AnimeListRouter: NSObject, AnimeListRoutingLogic, AnimeListDataPassing
{
  weak var viewController: AnimeListController?
  var dataStore: AnimeListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AnimeListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AnimeListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
