//
//  AnimeListWorker.swift
//  Codable_Clean
//
//  Created by OuSS on 5/11/19.
//  Copyright (c) 2019 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AnimeListWorker {
    
    func fetchAnimes(completion: @escaping (_ result: Result<Animes.List.Response,Error>) -> Void) {
        AnimeService.instance.getAnimeList { (result) in
            completion(result)
        }
    }
}
