//
//  AnimeListInteractor.swift
//  Codable_Clean
//
//  Created by OuSS on 5/11/19.
//  Copyright (c) 2019 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnimeListBusinessLogic
{
  func getAnimes(request: Animes.List.Request)
}

protocol AnimeListDataStore
{
  //var name: String { get set }
}

class AnimeListInteractor: AnimeListBusinessLogic, AnimeListDataStore
{
  var presenter: AnimeListPresentationLogic?
  var worker: AnimeListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func getAnimes(request: Animes.List.Request)
  {
    worker = AnimeListWorker()
    worker?.fetchAnimes(completion: { (result) in
        switch result {
        case .success(let season):
            self.presenter?.presentAnimes(response: season)
        case .failure(_):
            let response = Animes.List.Response(animes: nil)
            self.presenter?.presentAnimes(response: response)
        }
    })    
  }
}
