//
//  AnimeListModels.swift
//  Codable_Clean
//
//  Created by OuSS on 5/11/19.
//  Copyright (c) 2019 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Animes
{
    // MARK: Use cases
    struct Anime: Codable {
        let title: String
        let imageUrl: String
        let synopsis: String
        
        enum CodingKeys: String, CodingKey {
            case title
            case imageUrl = "image_url"
            case synopsis
        }
    }
  
  enum List {
    struct Request {
        
    }
    
    struct Response: Codable {
        var animes: [Anime]?
        
        enum CodingKeys: String, CodingKey {
            case animes = "anime"
        }
    }
    
    struct ViewModel {
        var animes: [Anime]?
    }
  }
}
