//
//  AnimeListPresenter.swift
//  Codable_Clean
//
//  Created by OuSS on 5/11/19.
//  Copyright (c) 2019 OuSS. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AnimeListPresentationLogic
{
  func presentAnimes(response: Animes.List.Response)
}

class AnimeListPresenter: AnimeListPresentationLogic
{
  weak var viewController: AnimeListDisplayLogic?
  
  // MARK: Do something
  
  func presentAnimes(response: Animes.List.Response)
  {
    var viewModel = Animes.List.ViewModel()
    viewModel.animes = response.animes
    viewController?.displayAnimes(viewModel: viewModel)
  }
}
